### ISSUE TITLE
Create responsive UI

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#13] opened 2024-10-24 09:43 UTC
### This issues is part of ODHACK 9.0, apply via the platform

Create responsive UI

Please ensure to provide an ETA.

https://www.figma.com/design/dwXPww5jcUl55azC9EQ8H0/SCANGUARD?node-id=14-12&t=CY2laF37qFH954NR-1

Looking forward to seeing your great work!

**Comment by NueloSE** [comment] 2024-10-24 09:46
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
am a frontend developer

### How I plan on tackling this issue
ETA <= 72hrs

**Comment by martinvibes** [comment] 2024-10-24 09:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by CollinsC1O** [comment] 2024-10-24 09:50
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and I will love to take on this

**Comment by Benjtalkshow** [comment] 2024-10-24 09:56
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will create a responsive user interface based on the provided design specifications in the Figma link. My focus will be on ensuring that the UI is visually appealing and functional across a range of devices and screen sizes, adhering closely to the design details outlined in the Figma file.

To achieve this, I will implement a flexible layout that adapts seamlessly to different resolutions, making use of media queries and responsive design techniques. I will also prioritize user experience by ensuring that all elements remain accessible and usable, regardless of the device.
I look forward to delivering a polished and responsive UI that meets the expectations set forth in the project requirements. Thank you for the opportunity.
My ETA is 3days.

**Comment by ooochoche** [comment] 2024-10-24 10:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I Have a strong background as UI designer


### How I plan on tackling this issue
Make the design responsive

**Comment by 0xdevcollins** [comment] 2024-10-24 10:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
ETA: 24hrs
To create a responsive UI based on the provided Figma design for the SCANGUARD project, I'll first analyze the design elements and layout to understand how the UI should adapt across different screen sizes. I'll adopt a mobile-first approach, starting with styles for smaller screens to ensure the layout is clean and functional on mobile devices.

Next, I'll implement CSS Flexbox or Grid for layout management, allowing elements to resize and rearrange as needed. Media queries will be added to adjust styles at various breakpoints, ensuring the UI looks good on tablets and desktops as well. I will also ensure that buttons and interactive elements are large enough for easy tapping on mobile devices.

Once the initial implementation is complete, I'll conduct thorough testing across different devices and screen sizes to ensure everything is responsive and functional.

**Comment by mimisavage** [comment] 2024-10-24 10:10
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hi, I’m Mimi Sav, a frontend and blockchain developer. This is my first time contributing to this repository, and I'm excited about the opportunity to collaborate.



### How I plan on tackling this issue
To tackle the task of creating a responsive UI based on the provided Figma design, I will first review the design elements and layout specifications. I will then implement a mobile-first approach using CSS Flexbox and Grid to ensure adaptability across devices. Testing will be conducted across various screen sizes to ensure consistency and usability.

ETA: 24hrs.
 Looking forward to delivering a polished product

**Comment by DanielEmmanuel1** [comment] 2024-10-24 10:24
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello, my name is Deon, I’m a Full stack web3 developer with a strong passion for creating intuitive and user-friendly interfaces. I have experience in modern JavaScript frameworks as well as ample expereience in CSS and frameworks like taiwind, bootstrap, scss amongst others, which allows me to effectively translate design concepts into functional web applications.

### How I plan on tackling this issue
-Firstly, I’ll take a close look at the Figma design to get a good understanding of the layout, components, and how they need to behave responsively.

- Next, I’ll break the design into key sections (like header, main content, etc.) and plan how each part will adapt smoothly across different screen sizes, from desktops down to mobile devices.

- Once that’s mapped out, I’ll dive into the coding phase, using techniques like media queries, flexbox, and grids to make sure the layout adjusts fluidly.

- I'll also make sure that all the UI elements—buttons, forms, and images—are responsive and user-friendly, with accessibility in mind.

- After the coding is done, I’ll test everything on multiple devices and screens (desktop, tablet, mobile) to make sure it all functions as intended and looks great.

- Based on those tests, I'll make any necessary tweaks to ensure everything is aligned and works perfectly.

- Finally, I’ll open a PR and await review from the team.

**Closed** 2024-10-27 22:53 UTC
Labels: good first issue, design, ODHack9
