### ISSUE TITLE
Design user dashboard screen 

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#9] opened 2024-10-23 13:30 UTC
Thanks you for showing interest!

https://www.figma.com/design/dwXPww5jcUl55azC9EQ8H0/SCANGUARD?node-id=14-12&t=CY2laF37qFH954NR-1

Please ensure to provide an ETA.

Looking forward to seeing your great work!

**Comment by sajalbnl** [comment] 2024-10-23 15:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am an Android developer with 2 years of experience in Kotlin, Jetpack Compose, and MVVM architecture. I’ve contributed to StarkNet Phone, building wallet and light client apps by integrating APIs and implementing UI/UX features. I'm excited to contribute my skills to this project . ETA - 1DAY

### How I plan on tackling this issue
I Will use jetpack compose to design screens in kotlin for mobile application

**Comment by CollinsC1O** [comment] 2024-10-23 18:25
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello I am a front-end and a blockchain developer. I will love to work on this issue.

**Comment by jedstroke** [comment] 2024-10-23 19:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a seasoned fullstack web3 developer with a knack for crafting pixel-perfect UI designs.  Here's my lil' portfolio: https://www.jedshock.com

### How I plan on tackling this issue
ETA: 2.5 - 4 days
I can tackle this issue easy, and mindfully.

**Comment by josephchimebuka** [comment] 2024-10-24 02:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will build the dashboard to fit the UI design every pixels made perfect in 3-4 days

**Comment by 0xdevcollins** [comment] 2024-10-24 07:34
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
I will implement the design carefully.
ETA: 48hrs

**Comment by Ayoazeez26** [comment] 2024-10-24 07:46
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Following the guide provided in the figma link, I will design the dashboard screen
ETA - 4 days

**Comment by Benjtalkshow** [comment] 2024-10-24 08:37
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will design the user dashboard screen based on the provided Figma link. The dashboard will be user-friendly, visually appealing, and in line with the project’s overall design language. I will focus on ensuring that all essential elements are easy to access and interact with.

My (ETA) for the design is 3 days. This will allow time for iterations and feedback to ensure that the final design meets all requirements and expectations.

**Comment by Ugo-X** [comment] 2024-10-24 08:43
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
will be sure to produce an exact replica of the figma design. 
ETA is 2 days

**Comment by ShantelPeters** [comment] 2024-10-24 09:26
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
My background in front-end development and UI/UX design allows me to effectively translate designs into functional applications while ensuring a user-friendly experience.

### How I plan on tackling this issue
To approach this design implementation based on the provided Figma link, I would first thoroughly review the design elements, including layout, typography, color schemes, and interactive components. I would then set up the development environment, ensuring that any necessary frameworks or libraries are in place for a seamless integration of the design.

Next, I would break down the implementation into manageable tasks, prioritizing key components such as responsive layouts, accessibility, and user interaction functionality. I would ensure that the design adheres to the guidelines specified in the Figma file while maintaining responsiveness across various devices.

For an estimated timeline, I would aim to complete the initial implementation within **3-5 working days , allowing time for revisions based on feedback and thorough testing to ensure all elements function as intended.

My background in front-end development and UI/UX design allows me to effectively translate designs into functional applications while ensuring a user-friendly experience.

**Comment by Calebux** [comment] 2024-10-24 09:52
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I have strong ux backaground

### How I plan on tackling this issue
Design screen according to product guidelines 
ETA 2days

**Comment by DanielEmmanuel1** [comment] 2024-10-24 10:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Good day, my name is Deon and I’m a Full-Stack web3 developer with a strong passion for creating intuitive and user-friendly interfaces. 

I have experience in writing Typescript as well as modern JavaScript and its frameworks and a keen eye for design, which allows me to effectively translate design concepts into functional web applications. 

### How I plan on tackling this issue
- First, I’ll carefully go through the Figma design you provided to fully understand the user dashboard layout and the specific features you want included.

- After that, I’ll break it down into different components, like navigation, user stats, charts, etc., and figure out the best way to implement each section to ensure it's functional and visually appealing.

- Once everything is planned out, I’ll start coding the dashboard, making sure that it’s responsive and user-friendly on all devices.

- After coding, I’ll do a thorough test of the dashboard, making sure everything works as expected and looks clean across various screen sizes.

- Based on testing, I’ll tweak any parts that need improvement to make sure the user experience is smooth and intuitive.

- Finally, I’ll create a PR for review from team, and I’ll make any necessary adjustments based on the feedback.

- If assigned I can start the design today and complete it max of 48 hours.

**Comment by EjembiEmmanuel** [comment] 2024-10-24 10:40
@Calebux assigned you. Goodluck!

**Closed** 2024-10-30 11:08 UTC
Labels: good first issue, design, ODHack9, urgent
