### ISSUE TITLE
Design Landing Page screen 

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#7] opened 2024-10-23 13:17 UTC
https://www.figma.com/design/dwXPww5jcUl55azC9EQ8H0/SCANGUARD?node-id=14-12&t=CY2laF37qFH954NR-1

Please ensure to provide an ETA.

Looking forward to seeing your great work!

**Comment by martinvibes** [comment] 2024-10-23 14:00
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello I'm a frontend and blockchain d3v and I will like to work on this issue :)

### How I plan on tackling this issue
I would make sure to look at the design properly and implement it to pixel perfect

ETA: 3 days

**Comment by CollinsC1O** [comment] 2024-10-23 18:24
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello I am a front-end and a blockchain developer. I will love to work on this issue please assign. I can handle this

**Comment by jedstroke** [comment] 2024-10-23 19:28
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a seasoned fullstack web3 developer with a knack for crafting pixel-perfect UI designs.  Here's my lil' portfolio: https://www.jedshock.com

### How I plan on tackling this issue
ETA: 1 - 2 days
I can tackle this issue easy, and mindfully.

**Comment by josephchimebuka** [comment] 2024-10-24 02:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I would follow the figma UI and design the landing page screen in 3 days

**Comment by Otaiki1** [comment] 2024-10-24 07:18
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello i am a fullstack developer with experience with building dapps. I am super eager to contribute to this project as i have built a lot of landing pages .

### How I plan on tackling this issue
I would follow the style file dilligiently and ensure everything works as described.

**Comment by Osatuyi** [comment] 2024-10-24 07:26
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Can I be assigned this issue.

### How I plan on tackling this issue
I'll create a design system and come up with a functional UI

**Comment by Akshola00** [comment] 2024-10-24 07:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
 I am a software developer with strong frontend expertise, specializing in responsive user interfaces and web applications. My skills include UI/UX optimization and modern frontend frameworks, allowing me to deliver efficient, user-friendly solutions.

### How I plan on tackling this issue
I will analyze the Figma design files to understand the layout and components, then implement the user interface with reusable components, ensuring responsiveness and design fidelity. I will make sure to test across different screen sizes and browsers.

**Comment by Ayoazeez26** [comment] 2024-10-24 07:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
ETA - 3 days

**Comment by Benjtalkshow** [comment] 2024-10-24 08:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will design the Landing Page screen based on the provided Figma link. My goal is to ensure that the design closely matches the layout, styles, and assets specified in the Figma file. I will focus on maintaining pixel-perfect accuracy, as well as ensuring the design is fully responsive to provide an optimal user experience across various devices.

I will pay careful attention to details, including typography, color schemes, and element spacing, to align with the design specifications. Additionally, I will incorporate best practices for accessibility to make sure the landing page is user-friendly for everyone.
My ETA is 3days.

**Comment by Ugo-X** [comment] 2024-10-24 08:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
ETA is 2 days

**Comment by ShantelPeters** [comment] 2024-10-24 09:33
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I will leverage my background in UI/UX design and development to create a user-friendly interface that aligns with the project’s goals. My experience with responsive design ensures that the application will function seamlessly across various devices, enhancing the user experience. I will follow the Figma specifications closely, ensuring that all elements are implemented accurately, including color schemes, typography, and layout.



### How I plan on tackling this issue
To approach this design implementation based on the provided Figma link for the SCANGUARD project, I would follow these steps:

1. Familiarize with the Design: Carefully review the Figma design to understand the layout, color scheme, typography, and overall visual elements. 

2. Set Up the Development Environment: Ensure that the development environment is ready, including any necessary frameworks and libraries.

3. Break Down the Components: Identify key components from the design, such as headers, footers, buttons, forms, and any custom elements. Create a list of these components for systematic implementation.

4. Implement the UI: Start coding the components using appropriate technologies (e.g., React, Angular, etc.). Ensure that the design specifications, such as dimensions, margins, and paddings, are accurately followed.

5. Ensure Responsiveness: Use CSS techniques (like Flexbox or Grid) to make the design responsive across different devices. Test on various screen sizes to ensure compatibility.

6. Test Functionality: Implement any interactive elements, ensuring they function as intended. This includes validating form inputs and handling user interactions.

7. Code Review and Iteration: After the initial implementation, review the code for best practices and performance. Make any necessary adjustments based on feedback or testing results.

8. Deployment Preparation: Prepare the code for deployment, ensuring it meets any project-specific guidelines or requirements.

9. ETA: Based on the complexity of the design and the steps involved, I would estimate a timeline of approximately [3-5 days ] for completion, including testing and revisions.

**Comment by ooochoche** [comment] 2024-10-24 09:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I Have a strong background as UI designer

### How I plan on tackling this issue
Design the landing page according to project vision and brand guidelines.
ETA 24hrs

**Comment by jancris100** [comment] 2024-10-24 10:19
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm from dojo coding with 2 years of experience in web developer

### How I plan on tackling this issue
I have a lot experience made views and land page so this have not presented a problem to ne

**Closed** 2024-10-27 23:04 UTC
Labels: good first issue, design, ODHack9, urgent
